# Generated by Django 4.0.2 on 2022-02-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_corte', models.CharField(max_length=100)),
                ('valor_corte', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
