# Generated by Django 4.0.2 on 2022-02-19 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cortes', '0002_corte_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='corte',
            name='foto_corte',
            field=models.ImageField(blank=True, upload_to='fotos/%d/%m/%Y/'),
        ),
    ]
